### ISSUE TITLE
All versions up to v.0.0.7.0 are crashing on Win7

### ISSUE THREAD

**Issue by tantoinet** [kacos2000/Prefetch-Browser#2]
All versions up to v.0.0.7.0 are crashing on Win7 x64. Is this expected to work on Win7? Which .NET Framework is it advised to run on?
Details from the crash UI:
`Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	PrefetchBrowser.exe
  Problem Signature 02:	0.0.7.0
  Problem Signature 03:	602bc6f9
  Problem Signature 04:	PoshExeHostWinV5
  Problem Signature 05:	0.0.7.0
  Problem Signature 06:	602bc6f9
  Problem Signature 07:	3c
  Problem Signature 08:	87
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	fdc5
  Additional Information 2:	fdc51d2c66af9ab3d2cf6cf3252915ec
  Additional Information 3:	e201
  Additional Information 4:	e201afc90b8923e95bd6d39a4817f2e0

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
`

Same for MFT Browser.

**Comment by kacos2000** [comment]
Should work fine with any Windows 10/11 x64 version. 
Dependencies: 
[.NET Framework 4.8](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48)
[Powershell Version:  5.1](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/install/windows-powershell-system-requirements?view=powershell-5.1)
